package api_test

// 5 data for repositories
const mockRepositories = `[
  {
    "id": 489517307,
    "node_id": "R_kgDOHS1w-w",
    "name": "account-book-api",
    "full_name": "kokoichi206/account-book-api",
    "private": false,
    "owner": {
      "login": "kokoichi206",
      "id": 52474650,
      "node_id": "MDQ6VXNlcjUyNDc0NjUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/52474650?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kokoichi206",
      "html_url": "https://github.com/kokoichi206",
      "followers_url": "https://api.github.com/users/kokoichi206/followers",
      "following_url": "https://api.github.com/users/kokoichi206/following{/other_user}",
      "gists_url": "https://api.github.com/users/kokoichi206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kokoichi206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kokoichi206/subscriptions",
      "organizations_url": "https://api.github.com/users/kokoichi206/orgs",
      "repos_url": "https://api.github.com/users/kokoichi206/repos",
      "events_url": "https://api.github.com/users/kokoichi206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kokoichi206/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/kokoichi206/account-book-api",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/kokoichi206/account-book-api",
    "forks_url": "https://api.github.com/repos/kokoichi206/account-book-api/forks",
    "keys_url": "https://api.github.com/repos/kokoichi206/account-book-api/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kokoichi206/account-book-api/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kokoichi206/account-book-api/teams",
    "hooks_url": "https://api.github.com/repos/kokoichi206/account-book-api/hooks",
    "issue_events_url": "https://api.github.com/repos/kokoichi206/account-book-api/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kokoichi206/account-book-api/events",
    "assignees_url": "https://api.github.com/repos/kokoichi206/account-book-api/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kokoichi206/account-book-api/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kokoichi206/account-book-api/tags",
    "blobs_url": "https://api.github.com/repos/kokoichi206/account-book-api/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kokoichi206/account-book-api/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kokoichi206/account-book-api/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kokoichi206/account-book-api/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kokoichi206/account-book-api/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kokoichi206/account-book-api/languages",
    "stargazers_url": "https://api.github.com/repos/kokoichi206/account-book-api/stargazers",
    "contributors_url": "https://api.github.com/repos/kokoichi206/account-book-api/contributors",
    "subscribers_url": "https://api.github.com/repos/kokoichi206/account-book-api/subscribers",
    "subscription_url": "https://api.github.com/repos/kokoichi206/account-book-api/subscription",
    "commits_url": "https://api.github.com/repos/kokoichi206/account-book-api/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kokoichi206/account-book-api/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kokoichi206/account-book-api/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kokoichi206/account-book-api/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kokoichi206/account-book-api/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kokoichi206/account-book-api/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kokoichi206/account-book-api/merges",
    "archive_url": "https://api.github.com/repos/kokoichi206/account-book-api/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kokoichi206/account-book-api/downloads",
    "issues_url": "https://api.github.com/repos/kokoichi206/account-book-api/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kokoichi206/account-book-api/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kokoichi206/account-book-api/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kokoichi206/account-book-api/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kokoichi206/account-book-api/labels{/name}",
    "releases_url": "https://api.github.com/repos/kokoichi206/account-book-api/releases{/id}",
    "deployments_url": "https://api.github.com/repos/kokoichi206/account-book-api/deployments",
    "created_at": "2022-05-06T23:19:06Z",
    "updated_at": "2022-05-09T14:06:49Z",
    "pushed_at": "2022-05-22T14:11:36Z",
    "git_url": "git://github.com/kokoichi206/account-book-api.git",
    "ssh_url": "git@github.com:kokoichi206/account-book-api.git",
    "clone_url": "https://github.com/kokoichi206/account-book-api.git",
    "svn_url": "https://github.com/kokoichi206/account-book-api",
    "homepage": null,
    "size": 134,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Go",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 7,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 7,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 490295663,
    "node_id": "R_kgDOHTlRbw",
    "name": "account-book-ios",
    "full_name": "kokoichi206/account-book-ios",
    "private": false,
    "owner": {
      "login": "kokoichi206",
      "id": 52474650,
      "node_id": "MDQ6VXNlcjUyNDc0NjUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/52474650?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kokoichi206",
      "html_url": "https://github.com/kokoichi206",
      "followers_url": "https://api.github.com/users/kokoichi206/followers",
      "following_url": "https://api.github.com/users/kokoichi206/following{/other_user}",
      "gists_url": "https://api.github.com/users/kokoichi206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kokoichi206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kokoichi206/subscriptions",
      "organizations_url": "https://api.github.com/users/kokoichi206/orgs",
      "repos_url": "https://api.github.com/users/kokoichi206/repos",
      "events_url": "https://api.github.com/users/kokoichi206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kokoichi206/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/kokoichi206/account-book-ios",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/kokoichi206/account-book-ios",
    "forks_url": "https://api.github.com/repos/kokoichi206/account-book-ios/forks",
    "keys_url": "https://api.github.com/repos/kokoichi206/account-book-ios/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kokoichi206/account-book-ios/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kokoichi206/account-book-ios/teams",
    "hooks_url": "https://api.github.com/repos/kokoichi206/account-book-ios/hooks",
    "issue_events_url": "https://api.github.com/repos/kokoichi206/account-book-ios/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kokoichi206/account-book-ios/events",
    "assignees_url": "https://api.github.com/repos/kokoichi206/account-book-ios/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kokoichi206/account-book-ios/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kokoichi206/account-book-ios/tags",
    "blobs_url": "https://api.github.com/repos/kokoichi206/account-book-ios/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kokoichi206/account-book-ios/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kokoichi206/account-book-ios/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kokoichi206/account-book-ios/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kokoichi206/account-book-ios/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kokoichi206/account-book-ios/languages",
    "stargazers_url": "https://api.github.com/repos/kokoichi206/account-book-ios/stargazers",
    "contributors_url": "https://api.github.com/repos/kokoichi206/account-book-ios/contributors",
    "subscribers_url": "https://api.github.com/repos/kokoichi206/account-book-ios/subscribers",
    "subscription_url": "https://api.github.com/repos/kokoichi206/account-book-ios/subscription",
    "commits_url": "https://api.github.com/repos/kokoichi206/account-book-ios/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kokoichi206/account-book-ios/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kokoichi206/account-book-ios/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kokoichi206/account-book-ios/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kokoichi206/account-book-ios/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kokoichi206/account-book-ios/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kokoichi206/account-book-ios/merges",
    "archive_url": "https://api.github.com/repos/kokoichi206/account-book-ios/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kokoichi206/account-book-ios/downloads",
    "issues_url": "https://api.github.com/repos/kokoichi206/account-book-ios/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kokoichi206/account-book-ios/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kokoichi206/account-book-ios/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kokoichi206/account-book-ios/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kokoichi206/account-book-ios/labels{/name}",
    "releases_url": "https://api.github.com/repos/kokoichi206/account-book-ios/releases{/id}",
    "deployments_url": "https://api.github.com/repos/kokoichi206/account-book-ios/deployments",
    "created_at": "2022-05-09T13:29:40Z",
    "updated_at": "2022-07-21T08:10:33Z",
    "pushed_at": "2022-05-21T04:57:46Z",
    "git_url": "git://github.com/kokoichi206/account-book-ios.git",
    "ssh_url": "git@github.com:kokoichi206/account-book-ios.git",
    "clone_url": "https://github.com/kokoichi206/account-book-ios.git",
    "svn_url": "https://github.com/kokoichi206/account-book-ios",
    "homepage": null,
    "size": 39,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Swift",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 6,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 6,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 517139735,
    "node_id": "R_kgDOHtLtFw",
    "name": "action-URL-watcher",
    "full_name": "kokoichi206/action-URL-watcher",
    "private": false,
    "owner": {
      "login": "kokoichi206",
      "id": 52474650,
      "node_id": "MDQ6VXNlcjUyNDc0NjUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/52474650?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kokoichi206",
      "html_url": "https://github.com/kokoichi206",
      "followers_url": "https://api.github.com/users/kokoichi206/followers",
      "following_url": "https://api.github.com/users/kokoichi206/following{/other_user}",
      "gists_url": "https://api.github.com/users/kokoichi206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kokoichi206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kokoichi206/subscriptions",
      "organizations_url": "https://api.github.com/users/kokoichi206/orgs",
      "repos_url": "https://api.github.com/users/kokoichi206/repos",
      "events_url": "https://api.github.com/users/kokoichi206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kokoichi206/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/kokoichi206/action-URL-watcher",
    "description": "Detect HTML contents change",
    "fork": false,
    "url": "https://api.github.com/repos/kokoichi206/action-URL-watcher",
    "forks_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/forks",
    "keys_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/teams",
    "hooks_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/hooks",
    "issue_events_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/events",
    "assignees_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/tags",
    "blobs_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/languages",
    "stargazers_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/stargazers",
    "contributors_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/contributors",
    "subscribers_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/subscribers",
    "subscription_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/subscription",
    "commits_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/merges",
    "archive_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/downloads",
    "issues_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/labels{/name}",
    "releases_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/releases{/id}",
    "deployments_url": "https://api.github.com/repos/kokoichi206/action-URL-watcher/deployments",
    "created_at": "2022-07-23T18:51:39Z",
    "updated_at": "2022-07-27T01:57:09Z",
    "pushed_at": "2022-07-24T19:08:37Z",
    "git_url": "git://github.com/kokoichi206/action-URL-watcher.git",
    "ssh_url": "git@github.com:kokoichi206/action-URL-watcher.git",
    "clone_url": "https://github.com/kokoichi206/action-URL-watcher.git",
    "svn_url": "https://github.com/kokoichi206/action-URL-watcher",
    "homepage": null,
    "size": 6,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main"
  },
  {
    "id": 453613576,
    "node_id": "R_kgDOGwmYCA",
    "name": "actions-diff-and-notify",
    "full_name": "kokoichi206/actions-diff-and-notify",
    "private": false,
    "owner": {
      "login": "kokoichi206",
      "id": 52474650,
      "node_id": "MDQ6VXNlcjUyNDc0NjUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/52474650?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kokoichi206",
      "html_url": "https://github.com/kokoichi206",
      "followers_url": "https://api.github.com/users/kokoichi206/followers",
      "following_url": "https://api.github.com/users/kokoichi206/following{/other_user}",
      "gists_url": "https://api.github.com/users/kokoichi206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kokoichi206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kokoichi206/subscriptions",
      "organizations_url": "https://api.github.com/users/kokoichi206/orgs",
      "repos_url": "https://api.github.com/users/kokoichi206/repos",
      "events_url": "https://api.github.com/users/kokoichi206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kokoichi206/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/kokoichi206/actions-diff-and-notify",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify",
    "forks_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/forks",
    "keys_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/teams",
    "hooks_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/hooks",
    "issue_events_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/events",
    "assignees_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/tags",
    "blobs_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/languages",
    "stargazers_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/stargazers",
    "contributors_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/contributors",
    "subscribers_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/subscribers",
    "subscription_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/subscription",
    "commits_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/merges",
    "archive_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/downloads",
    "issues_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/labels{/name}",
    "releases_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/releases{/id}",
    "deployments_url": "https://api.github.com/repos/kokoichi206/actions-diff-and-notify/deployments",
    "created_at": "2022-01-30T07:17:13Z",
    "updated_at": "2022-01-30T07:18:44Z",
    "pushed_at": "2022-02-23T09:34:22Z",
    "git_url": "git://github.com/kokoichi206/actions-diff-and-notify.git",
    "ssh_url": "git@github.com:kokoichi206/actions-diff-and-notify.git",
    "clone_url": "https://github.com/kokoichi206/actions-diff-and-notify.git",
    "svn_url": "https://github.com/kokoichi206/actions-diff-and-notify",
    "homepage": null,
    "size": 185,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Kotlin",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 384782545,
    "node_id": "MDEwOlJlcG9zaXRvcnkzODQ3ODI1NDU=",
    "name": "ai_web_app_flask",
    "full_name": "kokoichi206/ai_web_app_flask",
    "private": false,
    "owner": {
      "login": "kokoichi206",
      "id": 52474650,
      "node_id": "MDQ6VXNlcjUyNDc0NjUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/52474650?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kokoichi206",
      "html_url": "https://github.com/kokoichi206",
      "followers_url": "https://api.github.com/users/kokoichi206/followers",
      "following_url": "https://api.github.com/users/kokoichi206/following{/other_user}",
      "gists_url": "https://api.github.com/users/kokoichi206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kokoichi206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kokoichi206/subscriptions",
      "organizations_url": "https://api.github.com/users/kokoichi206/orgs",
      "repos_url": "https://api.github.com/users/kokoichi206/repos",
      "events_url": "https://api.github.com/users/kokoichi206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kokoichi206/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/kokoichi206/ai_web_app_flask",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask",
    "forks_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/forks",
    "keys_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/teams",
    "hooks_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/hooks",
    "issue_events_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/events",
    "assignees_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/tags",
    "blobs_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/languages",
    "stargazers_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/stargazers",
    "contributors_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/contributors",
    "subscribers_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/subscribers",
    "subscription_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/subscription",
    "commits_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/merges",
    "archive_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/downloads",
    "issues_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/labels{/name}",
    "releases_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/releases{/id}",
    "deployments_url": "https://api.github.com/repos/kokoichi206/ai_web_app_flask/deployments",
    "created_at": "2021-07-10T20:18:00Z",
    "updated_at": "2021-07-11T06:58:53Z",
    "pushed_at": "2021-07-11T06:58:51Z",
    "git_url": "git://github.com/kokoichi206/ai_web_app_flask.git",
    "ssh_url": "git@github.com:kokoichi206/ai_web_app_flask.git",
    "clone_url": "https://github.com/kokoichi206/ai_web_app_flask.git",
    "svn_url": "https://github.com/kokoichi206/ai_web_app_flask",
    "homepage": null,
    "size": 6417,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Python",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  }
]
`

// Expected to fail Unmarshal
const mockRepositoriesWithEmpty = `[
  {
    "id": 489517307,
    "name": "account-book-api",
    "full_name": "kokoichi206/account-book-api",
  },
  {
    "id": 490295663,
    "name": "account-book-ios",
    "full_name": "kokoichi206/account-book-ios",
    "private": false,
  },
  {
    "id": 517139735,
    "name": "action-URL-watcher",
    "full_name": "kokoichi206/action-URL-watcher",
    "private": false,
  },
  {
    "id": 453613576,
    "name": "actions-diff-and-notify",
    "full_name": "kokoichi206/actions-diff-and-notify",
    "private": false,
  },
  {
    "id": 384782545,
    "node_id": "MDEwOlJlcG9zaXRvcnkzODQ3ODI1NDU=",
    "name": "ai_web_app_flask",
  }
]
`

const unAuthorizedRequestMessage = `{
  "message": "Requires authentication",
  "documentation_url": "https://docs.github.com/rest/reference/repos#list-repositories-for-the-authenticated-user"
}`

const mockCodeFrequencies = `[
	[
	  1625961600,
	  4381719,
	  -9488
	],
	[
	  1626566400,
	  23550,
	  -208
	],
	[
	  1627171200,
	  3375,
	  -813
	]
]`

const codeFrequenciesUnmarshalError = `[
	[
	  1625961600,
	  4381719,
	  -9488
	],
	[
	  1626566400,
	  23550,
	  -208
	],
	[
	  "1627171200",
	  "3375",
	  -813
	]
]`
