name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install goreleaser
        run: |
          # see: https://goreleaser.com/install/
          brew install goreleaser
      - name: Create release using goreleaser
        run: |
          # see: https://goreleaser.com/quick-start/
          goreleaser release
